# Generated by Django 3.1 on 2020-08-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200815_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_customer',
            field=models.BooleanField(default=True, verbose_name='customer status'),
        ),
    ]
