# Generated by Django 3.1 on 2020-08-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200817_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='artist_image_url',
        ),
    ]
