# Generated by Django 3.1 on 2020-08-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
