# Generated by Django 3.1 on 2020-08-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_auto_20200810_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artists',
            old_name='name',
            new_name='artist',
        ),
    ]
