# Generated by Django 3.1 on 2020-08-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_auto_20200810_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='depth',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
