# Generated by Django 3.1 on 2020-08-11 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_auto_20200810_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
