# Generated by Django 3.1 on 2020-08-11 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_auto_20200811_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artists',
            old_name='artist',
            new_name='name',
        ),
    ]
