# Generated by Django 3.1 on 2020-08-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200815_1752'),
        ('artworks', '0009_auto_20200811_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='artist_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
            preserve_default=False,
        ),
    ]
