# Generated by Django 3.1 on 2020-08-17 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200817_0234'),
        ('artworks', '0010_artists_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
        migrations.DeleteModel(
            name='Artists',
        ),
    ]
