# Generated by Django 3.1 on 2020-08-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0012_auto_20200817_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.category'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='depth',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='depth (cm)'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='duration (mins)'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='length (cm)'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='weight (g)'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='width (cm)'),
        ),
    ]
